version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=spring
      - MYSQL_PASSWORD=spring
      - MYSQL_DATABASE=springbook
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"